language: android
jdk: oraclejdk8

android:
  components:
    - tools # repository-11
    - tools # upgrade tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'

script:
    - ./gradlew clean assemble test
